---
- name: for test
  hosts: franka
  user: eai
  become: yes
  become_method: sudo
  become_user: eai
  vars:
    local_file: /home/eai-amd/test02.py
    remote_file: /home/eai/test/

  tasks:
    - name: Copy a file
      ansible.builtin.copy:
        src: "{{ local_file }}"
        dest: "{{ remote_file }}"
        owner: eai
        group: eai
        mode: '0644'

    - name: List files in the remote directory
      ansible.builtin.command: ls -l "{{ remote_file }}"
      register: ls_output

    - name: Display the output of ls command
      ansible.builtin.debug:
        var: ls_output.stdout_lines

    - name: Find all .py files
      ansible.builtin.find:
        paths: "{{ remote_file }}"
        patterns: "*.py"
        recurse: no
      register: py_files

    - name: Remove all .py files
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: absent
      loop: "{{ py_files.files }}"
    
    - name: List files in the current directory
      command: ls test
      register: ls_output
    - name: Display the output of ls command
      debug:
        var: ls_output.stdout_lines